udistrital/titan_api_mid

.drone.yml

@fernandotower , @faparraf , @mariaalejandra9404 , @apdaza , plz check. thanks.

go get recursivo

---

controllers/gestion_contratos.go
controllers/services.go
controllers/utilidades.go
golog/utilidades.go
interceptor.go
main.go
models/desagregado_contrato_hcs.go
models/informacion_contrato_docente.go
routers/commentsRouter_controllers.go
routers/router.go

Se comienza desarrollo de servicio de docentes de hora catedra salarios para issue #54. Se agrega archivo interceptor e implementacin de auditoria para api mid

Servicio HCS. Implementación de auditoría

---

conf/app.conf
controllers/gestion_contratos.go
controllers/services.go
controllers/utilidades.go
golog/utilidades.go
interceptor.go
main.go
models/desagregado_contrato_hcs.go
models/informacion_contrato_docente.go
routers/commentsRouter_controllers.go
routers/router.go

Comienzo de servicio de HCS y prueba de auditoría en MID

---

controllers/preliquidacion.go

para depurar

---

controllers/preliquidacionct.go

ajuste fechas

---

conf/app.conf
controllers/preliquidacion.go
controllers/preliquidacionct.go
controllers/preliquidacionhch.go
controllers/preliquidacionhcs.go
golog/test_golog_nhc.go
golog/utilidades.go
routers/commentsRouter_controllers.go

#158 
Se hace el ajuste de reteiva para las personas naturales que son responsables de iva.

feature: ajuste reteiva

---

.drone.yml
conf/app.conf
controllers/detalle_preliquidacion.go
controllers/gestion_reportes.go
controllers/novedad.go
controllers/preliquidacion.go
controllers/ruler.go
golog/test_golog_nct.go
golog/test_golog_nhc.go

Se ajusta el drone para que la rama de preprod sea la rama release, además de eso se ajustan algunas comparaciones de ids con respecto a la creación del nuevo esquema de la base de datos

fix: ajuste de drone y comparacion de ids

---

conf/app.conf
controllers/novedad.go
golog/test_golog_nct.go

Al momento de registrar, activar y desactivar una novedad presentaba errores, todos fueron corregidos

fix: ajuste de metodos de registro y actualizacion

---

controllers/cumplido.go
controllers/novedad.go
models/otro_si.go
models/sucesor.go
models/suspension.go
routers/commentsRouter_controllers.go
swagger/swagger.json
swagger/swagger.yml

Se agregar la vigencia del contrato para tene run mejor manejo de cuál contrato recibe la novedad o el cumplido, ésto debido a que hay contratos con el mismo número pero los diferencia la vigencia

Fix: ajuste de cumplido y novedades contractuales

---

controllers/detalle_preliquidacion.go
controllers/novedad.go
controllers/preliquidacion.go
controllers/preliquidacionct.go
controllers/preliquidacionhch.go
controllers/utilidades.go
golog/test_golog_nct.go
routers/commentsRouter_controllers.go
swagger/swagger.json
swagger/swagger.yml

Se ajustan los métodos para calcular los días entre fechas, evitancdo así métodos y paramétors adicionales, así mismo se modificaron los endpoints de las novedades de valor y contractuales, además de verificar su funcionamiento

Fix: ajuste de preliquidacion

---

controllers/cumplido.go

Se ajusta el cumplido para que también se actualice el estado de preliquidación del contrato para el mes correspondiente

Fix: ajuste de cumplido

---

controllers/novedad.go
controllers/preliquidacion.go

Se dcrea condición para que la fecha de incio no que esté después de la fecha de fin y evitar un loop infinito

Fix: ajuste de comprobación de fechas de contratos

---

controllers/detalle_preliquidacion.go
models/detalle.go
swagger/swagger.json
swagger/swagger.yml

Ahora los contratos no se agrupan por resolución

Fix: ajuste de obtenciones de detalles DVE

---

controllers/novedad.go
controllers/preliquidacion.go
controllers/preliquidacionct.go
controllers/preliquidacionhcs.go
controllers/utilidades.go

Ahora se crea un contrato general por mes apra cada docente con el fin de liquidar de forma agrupada por el total de contratos que tiene.

Feat: agrupación de contratos de DVE

---

controllers/detalle_preliquidacion.go
controllers/novedad.go

Se ajusta la búsqueda del id del concepto en caso de que sea Salarios, debido a que este cambia

Fix: ajuste de novedades

---

controllers/contrato_preliquidacion.go
controllers/detalle_preliquidacion.go
controllers/novedad.go

Ahora cuando todos los cumplidos de los contratos están aprobados se acutaliza el cumplido del contrato general del mes para ese docente

Fix: ajuste de cumplido General

---

controllers/contrato_preliquidacion.go
controllers/detalle_preliquidacion.go
controllers/novedad.go

Ahora, cuando todos los cumplidos del docente se aprueben también lo hará el del contrato general, con el fin de poder sacar el reporte por aprobación de cumplidos

Fix: ajuste de contrato general

---

controllers/detalle_preliquidacion.go
controllers/gestion_contratos.go
controllers/preliquidacionhch.go
controllers/preliquidacionhcs.go
models/contrato.go
swagger/swagger.json
swagger/swagger.yml

Ahora en el contrato general, se liquida y se actualiza el valor de la retefuente, fondo solidaridad y fondo subsistencia de acuerdo al porcentaje de aporte por cada contrato (regla de 3)

Fix: ajuste de porcetanjes de descuentos de ley

---

controllers/detalle_preliquidacion.go
controllers/gestion_contratos.go
controllers/novedad.go
controllers/preliquidacionhch.go
controllers/preliquidacionhcs.go
models/contrato.go
swagger/swagger.json
swagger/swagger.yml

Ahora en el contrato general, se liquida y se actualiza el valor de la retefuente, fondo solidaridad y fondo subsistencia de acuerdo al porcentaje de aporte por cada contrato (regla de 3)

Fix: ajuste de descuentos de ley

---

controllers/preliquidacionhch.go
controllers/preliquidacionhcs.go

Se ajusta para que se ajusten los valores de los descuentos y demás valores a los cuales afecta el ibc una vez liquidado el contrato "general"

fix: ajuste de valor de descuentos DVE

---

controllers/desagregado_hcs.go
controllers/detalle_preliquidacion.go
controllers/novedad.go
controllers/preliquidacionct.go
controllers/utilidades.go
golog/golog_desagregado.go
models/datos_vinculacion.go
models/desagregado_contrato_hcs.go
models/objetoDocentePlanta.go
models/resolucion.go
models/vinculacion_docente.go
routers/commentsRouter_controllers.go
routers/router.go
swagger/swagger.json
swagger/swagger.yml

Se agregó un nuevo endpoint que permite calcular los valores desagregados de un contrato de VE en Salarios
Además de eso se corrigieron errores en las novedades de cesión en CPS que se daban cuando el contrato empieza un día 31

Feat: desagregado HCS

---

controllers/preliquidacionhcs.go
models/contrato.go
swagger/swagger.json
swagger/swagger.yml

Se han añadido nuevas reglas y condiciones para liquidar el ibc que se debe tener en cuenta para calcular el valor del aporte a caja de compensación familiar e icbf

Feat: liquidacion de "ibc 2" para caja e icbf

---

controllers/desagregado_hcs.go
controllers/preliquidacionhch.go

Se ajusta para que se liquide prima de servicios a tiempo completo ocasional y medio tiempo ocasional

Fix: ajuste desagragdo para VE salarios

---

controllers/novedad.go
controllers/preliquidacion.go
controllers/preliquidacionct.go
models/cancelacion.go
routers/commentsRouter_controllers.go
swagger/swagger.json
swagger/swagger.yml

Se ajusta la lógica de la novedad de cancelación en CPS, agregando manejo de errores

Feat: Lógica novedad cancelación CPS

---

controllers/preliquidacionhcs.go

Ajuste de liquidaciónde caja de compensación e icbf

Fix: ajuste de liquidación HCS

---

controllers/novedadCPS.go

Ajuste novedad otrosi

---

controllers/novedadCPS.go
controllers/novedadVE.go
models/reinicio.go
routers/commentsRouter_controllers.go

feat: Se desarrolla la novedad de reinicio udistrital/titan_cliente#214

---

controllers/novedadVE.go
controllers/preliquidacionhch.go
controllers/preliquidacionhcs.go
controllers/utilidades.go

feat: Ajustes contrato en novedad de anulacion

---

controllers/novedadVE.go
models/anulacion.go
swagger/swagger.json
swagger/swagger.yml

https://github.com/udistrital/resoluciones_cliente_v2/issues/137

feat: cancelacion posgrado 

---

controllers/novedadVE.go
controllers/preliquidacionhcs.go
controllers/utilidades.go
models/anulacion.go

udistrital/resoluciones_cliente_v2#160

fix: Cambios de cancelación y preliquidacion en anulacion

---

ScriptsReglas/HCSReglas.txt
controllers/desagregado_hcs.go
models/datos_vinculacion.go

Se modifica endpoint de calculo desagregado y ruler para contemplar calculo de prima de servicios en resoluciones de cancelacion

hotfix: Valor prima servicios cancelaciones TCO

---

controllers/preliquidacionhcs.go

Se agrega predicado cancelacion(0) por defecto para preliquidacionhcs

hotfix: Predicado de cancelacion por defecto

---

controllers/desagregado_hcs.go
models/datos_vinculacion.go

#499 Se cambia modelo DatosVinculacion para mejorar la gestion del cambio de valor del punto
https://github.com/udistrital/resoluciones_cliente_v2/issues/204

fix: Se pasa valor del punto en datos vinculacion
